# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none
jobs:
  - job: WebApp
    displayName: 'Build Web App'
    pool:
     vmImage: 'windows-2019'

    variables:
     buildConfiguration: 'Release'

    steps:
      
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '6.0.x'
        
      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: 'sonarcloud'
          organization: 'mysonarcube'
          scannerMode: 'MSBuild'
          projectKey: 'keyformysonarcube'
      
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: 'webapp/WebApp.csproj'
 
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: 'webapp/WebApp.csproj'
          arguments: '--configuration $(BuildConfiguration)'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          projects: 'WebApp.UnitTest/WebApp.UnitTest.csproj'
          arguments: '--configuration $(BuildConfiguration)'
        
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: true
          arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      - task: SonarCloudPublish@1
        inputs:
          pollingTimeoutSec: '300'
      
      - task: SonarCloudAnalyze@1
      
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
        
  - job: database
    displayName: 'database'
    pool:
     vmImage: 'windows-2019' 
    
    steps:
    - task: MSBuild@1
      inputs:
        solution: 'WebApp.Database/WebApp.Database.sqlproj'
        configuration: '/p:outdir=$(Build.ArtifactStagingDirectory)'

    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Dacpac'
        publishLocation: 'Container'
    
      
  - job: ui-test
    displayName: 'unit-test'  
    pool:
     vmimage: 'windows-2019'
    
    steps:
    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: 
    
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: 'WebAppWithDatabase.sln'
        feedsToUse: 'select'
        
    - task: MSBuild@1
      inputs:
        solution: 'SeleniumUiTests/SeleniumUiTests.csproj'
        msbuildArguments: '/p:outdir=$(Build.ArtifactStagingDirectory)'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'unit-test'
        publishLocation: 'Container'
  
  - job: infra
    displayName: "infra"   
    pool:
     vmimage: 'windows-2019'
    steps:
      - task: CopyPublishBuildArtifacts@1
        inputs:
          CopyRoot: 'AzureResourceGroupDeployment/AzureResourceGroupDeployment.deployproj'
          Contents: 'AzureResourceGroupDeployment.deployproj'
          ArtifactName: 'infra'
          ArtifactType: 'Container'
    
